#ifndef VEINSCRIPT_GLOBAL_H
#define VEINSCRIPT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VEINSCRIPT_LIBRARY)
#  define VEINSCRIPTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define VEINSCRIPTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // VEINSCRIPT_GLOBAL_H
